package com.mlwarren.web.filemanager.entity;

import com.fasterxml.jackson.annotation.JsonIgnore;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import lombok.*;

import javax.persistence.*;
import javax.validation.constraints.NotNull;
import java.util.List;

@ApiModel("User entity, may have one to many managed files")
@Entity
@NoArgsConstructor
public class User {


    @Getter
    @Id
    @GeneratedValue(strategy = GenerationType.AUTO)
    @ApiModelProperty(notes="ID generated by JPA")
    private Integer id;

    @Getter
    @Setter
    private String username;

    @JsonIgnore
    @Getter
    @Setter
    private String password;

    @Getter
    @Setter
    private String firstName;

    @Getter
    @Setter
    private String lastName;

    @Getter
    @Setter
    @ApiModelProperty(notes="Quota value measured in megabytes")
    private Integer quota;

    @Getter
    @Setter
    @ApiModelProperty(notes="List of managed files for the user")
    @OneToMany(mappedBy="user")
    private List<ManagedFile> files;

    @Override
    public String toString() {
        return "User{" +
                "id=" + id +
                ", username='" + username + '\'' +
                ", firstName='" + firstName + '\'' +
                ", lastName='" + lastName + '\'' +
                ", quota=" + quota +
                ", files=" + files +
                '}';
    }
}
